collections:
  projects:
    output: true
exclude: [node_modules, gulpfile.js, package.json]
socialLinks:
  - icon: linkedin
    url: "http://linkedin.com/in/mafeld"
  - icon: github
    url: "http://github.com/mattfeldman"
  - icon: twitter
    url: "http://twitter.com/mattfeldman"
  - icon: facebook
    url: "http://facebook.com/mattfeldman"
  - icon: medium
    url: "http://medium.com/@mattfeldman"
tags:
  languages:
    - C#
    - Javascript
    - Coffeescript
    - Java
    - LUA
    - Python
  frameworks:
    - Meteor
    - React
    - .net
    - ASP
    - Silverlight
  applications:
    - Visual Studio
    - SQL Server
    - Unity
    - Photoshop


